# Generated by Django 4.1 on 2023-06-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savinggoal',
            name='monthly_deposit_amount',
            field=models.FloatField(null=True),
        ),
    ]
