# Generated by Django 4.1 on 2023-06-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_savinggoal_monthly_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='savinggoal',
            name='current_date',
            field=models.DateField(null=True),
        ),
    ]
